version: 2
updates:
  - package-ecosystem: pub
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
    labels:
      - dependencies

  - package-ecosystem: gradle
    directory: "/android"
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
    labels:
      - dependencies
      - android

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore"
    labels:
      - dependencies
      - ci
